---

- name: install elasticsearch (debian)
  apt:
    name: elasticsearch-oss
    state: present
  when: ansible_os_family == 'Debian'

- name: install aelasticsearch (rhel)
  dnf:
    name: elasticsearch-oss
    state: present
    enablerepo: '{{ opencast_repository_identifiers }}'
    update_cache: true
  when: ansible_os_family == 'RedHat'

- name: start and enable elasticsearch service
  service:
    name: elasticsearch
    state: started
    enabled: true
